language: rust
rust: 
  - stable

cache:
  cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-dev
    - clang

script:
  - git submodule update --init --recursive
  - cargo run --release --bin avrio_database_test
  - cargo run --release --bin config_test
  - cargo run --release --bin txn_bench
  - cargo run --release --bin avrio_p2p

env:
  global:
  - RUST_BACKTRACE=1
  - CC="clang"
