[package]
name = "avrio_database_test"
version = "0.1.0"
edition = "2018"
authors = ["Leo Cornelius <leocornelius019@gmail.com>"]
license = "MIT OR Apache-2.0"
[bin]
name = "avrio-database-test"
source = "src/"
[dependencies]
avrio_database = { git: "https://github.com/avrio-project/avrio-core"
